### ISSUE TITLE
错别字问题

### ISSUE THREAD

**Issue by P-PPPP** [weiyinfu/MaoZeDongAnthology#6]
“162-永远保持艰苦奋斗的作风.md”中
“曾经使中共中央的所在地” 的 “使”应为“是”
检查过1977年的原文。望修复

![IMG_20210118_205129.jpg](https://i.loli.net/2021/01/18/s48DTyESlCYgtM2.jpg)

**Comment by peterpei1186861238** [comment]
![IMG_20210118_205129.jpg](https://i.loli.net/2021/01/18/s48DTyESlCYgtM2.jpg)
补图

**Comment by weiyinfu** [comment]
Thanks for the comment
